version: '3.8'
services:
  nginx:
    restart: always
    image: nginx:latest
    volumes:
#            - ./CryptoBro/static:/srv/www/CryptoBro/static
#            - ./CryptoBro/media:/srv/www/CryptoBro/media
            - ./CryptoBro/logs:/srv/www/CryptoBro/logs/
            - ./docker/nginx:/etc/nginx/conf.d/
            - ./docker/certbot:/var/www/certbot/    
    ports:
      - 80:8080
      - 443:443
    depends_on:
      - python
  certbot:
    image: certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - python
  python:
    restart: always
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./CryptoBro:/srv/www/CryptoBro
    expose:
      - 8000
    ports:
      - 8000:8000
    command: "gunicorn -c gunicorn.py CryptoBro.wsgi"